export const GET_SLIDESHOW_REQUEST = 'GET_SLIDESHOW_REQUEST';
export const GET_SLIDESHOW_SUCCESS = 'GET_SLIDESHOW_SUCCESS';
export const GET_SLIDESHOW_FAILURE = 'GET_SLIDESHOW_FAILURE';
export const GET_Food_SLIDESHOW_SUCCESS='GET_Food_SLIDESHOW_SUCCESS';
